# Welcome to Jekyll!

# Website settings
title: Marx's CV
description: An online website for my CV
keywords: Marx,Jalpc,blog,Jekyll,github,gh-pages
baseurl:  /homepage # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://marxlow.github.io/homepage/ # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /Jalpc/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: MarxLow  # Be used at blog posts' author.
  first_name: Marx  # Be used at index page about me section.
  last_name: Low  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: marxlow  # Leave blank if you don't have now
  linkedin_id: marx-low-8a15a6135 # Leave blank if you don't have now
  facebook_username:  # Leave blank if you don't have now
  twitter_username:  # Leave blank if you don't have now
  email: # Leave blank if you don't have now
  #cv: # A online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name:
    - name:
  skill_icon2:
    - name: 
    - name: 
  desc: Hey there! I am Marx, a Year 2 National University of Singapore(NUS) undergraduate pursuing a <b> Bachelor of Computing (Honours) in Computer Science.</b> <p>I am an independent learner and I have a passion in software development, algorithms, AI - In other words, almost all things Computer Science. I am also enthusiastic about the future where I can finally apply the skills I have learnt to better the lives of other people.</p><p>I aspire to one day be skilled enough to create a software product integrated with Artificial Intelligence(which I personally feel still has much untapped potential) to do just that, and an internship would be a step in the right direction.</p> # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# analytics
## google analytics
ga: # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## growingIO
gio: # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
